"""
    UnitAPI

    Edit the variables with your API Token and API Server.  You can create an API token in Unit Dashboard.   # noqa: E501

    The version of the OpenAPI document: dfec2411-22b5-4a3b-8d43-fcf778bd42a5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.cards_api import CardsApi  # noqa: E501


class TestCardsApi(unittest.TestCase):
    """CardsApi unit test stubs"""

    def setUp(self):
        self.api = CardsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_close(self):
        """Test case for close

        Close  # noqa: E501
        """
        pass

    def test_create_individual_debit_card(self):
        """Test case for create_individual_debit_card

        Create Individual Debit Card  # noqa: E501
        """
        pass

    def test_freeze(self):
        """Test case for freeze

        Freeze  # noqa: E501
        """
        pass

    def test_get12(self):
        """Test case for get12

        Get  # noqa: E501
        """
        pass

    def test_getall11(self):
        """Test case for getall11

        Get all  # noqa: E501
        """
        pass

    def test_patch_busienss_debit_card(self):
        """Test case for patch_busienss_debit_card

        Patch Busienss Debit Card  # noqa: E501
        """
        pass

    def test_patch_individual_debit_card(self):
        """Test case for patch_individual_debit_card

        Patch Individual Debit Card  # noqa: E501
        """
        pass

    def test_report_lost(self):
        """Test case for report_lost

        Report Lost  # noqa: E501
        """
        pass

    def test_report_stolen(self):
        """Test case for report_stolen

        Report Stolen  # noqa: E501
        """
        pass

    def test_unfreeze(self):
        """Test case for unfreeze

        Unfreeze  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
