"""
    UnitAPI

    Edit the variables with your API Token and API Server.  You can create an API token in Unit Dashboard.   # noqa: E501

    The version of the OpenAPI document: dfec2411-22b5-4a3b-8d43-fcf778bd42a5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.applications_api import ApplicationsApi  # noqa: E501


class TestApplicationsApi(unittest.TestCase):
    """ApplicationsApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_business(self):
        """Test case for create_business

        Create Business  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        Get  # noqa: E501
        """
        pass

    def test_getall(self):
        """Test case for getall

        Get all  # noqa: E501
        """
        pass

    def test_upload_document(self):
        """Test case for upload_document

        Upload Document  # noqa: E501
        """
        pass

    def test_upload_document_back(self):
        """Test case for upload_document_back

        Upload Document Back  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
