"""
    UnitAPI

    Edit the variables with your API Token and API Server.  You can create an API token in Unit Dashboard.   # noqa: E501

    The version of the OpenAPI document: dfec2411-22b5-4a3b-8d43-fcf778bd42a5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
200DataAttributesAddress
200DataAttributesAuthorizedUsers
200DataAttributesBeneficialOwners
200DataAttributesOfficer
200DataAttributesPhone
from openapi_client.model.200_data_attributes import 200DataAttributes


class Test200DataAttributes(unittest.TestCase):
    """200DataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test200DataAttributes(self):
        """Test 200DataAttributes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = 200DataAttributes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
