"""
    UnitAPI

    Edit the variables with your API Token and API Server.  You can create an API token in Unit Dashboard.   # noqa: E501

    The version of the OpenAPI document: dfec2411-22b5-4a3b-8d43-fcf778bd42a5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.batch_release_api import BatchReleaseApi  # noqa: E501


class TestBatchReleaseApi(unittest.TestCase):
    """BatchReleaseApi unit test stubs"""

    def setUp(self):
        self.api = BatchReleaseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_batch_release(self):
        """Test case for batch_release

        Batch Release  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
