"""
    UnitAPI

    Edit the variables with your API Token and API Server.  You can create an API token in Unit Dashboard.   # noqa: E501

    The version of the OpenAPI document: dfec2411-22b5-4a3b-8d43-fcf778bd42a5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.accounts_api import AccountsApi  # noqa: E501


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_deposit_account(self):
        """Test case for create_deposit_account

        Create Deposit Account  # noqa: E501
        """
        pass

    def test_get4(self):
        """Test case for get4

        Get  # noqa: E501
        """
        pass

    def test_getallby_customer_id(self):
        """Test case for getallby_customer_id

        Get all by Customer Id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
