"""
    UnitAPI

    Edit the variables with your API Token and API Server.  You can create an API token in Unit Dashboard.   # noqa: E501

    The version of the OpenAPI document: dfec2411-22b5-4a3b-8d43-fcf778bd42a5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.counterparties_api import CounterpartiesApi  # noqa: E501


class TestCounterpartiesApi(unittest.TestCase):
    """CounterpartiesApi unit test stubs"""

    def setUp(self):
        self.api = CounterpartiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_counterparty_bankdetails(self):
        """Test case for create_counterparty_bankdetails

        Create Counterparty - Bank details  # noqa: E501
        """
        pass

    def test_delete_counterparty(self):
        """Test case for delete_counterparty

        Delete Counterparty  # noqa: E501
        """
        pass

    def test_getall2(self):
        """Test case for getall2

        Get all  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
