"""
    UnitAPI

    Edit the variables with your API Token and API Server.  You can create an API token in Unit Dashboard.   # noqa: E501

    The version of the OpenAPI document: dfec2411-22b5-4a3b-8d43-fcf778bd42a5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.sandbox_api import SandboxApi  # noqa: E501


class TestSandboxApi(unittest.TestCase):
    """SandboxApi unit test stubs"""

    def setUp(self):
        self.api = SandboxApi()  # noqa: E501

    def tearDown(self):
        pass

    def test__sandbox_activate_card(self):
        """Test case for _sandbox_activate_card

        (Sandbox) Activate Card  # noqa: E501
        """
        pass

    def test__sandbox_approve_application(self):
        """Test case for _sandbox_approve_application

        (Sandbox) Approve Application  # noqa: E501
        """
        pass

    def test__sandbox_approve_document(self):
        """Test case for _sandbox_approve_document

        (Sandbox) Approve Document  # noqa: E501
        """
        pass

    def test__sandbox_clear_ach_payment(self):
        """Test case for _sandbox_clear_ach_payment

        (Sandbox) Clear ACH Payment  # noqa: E501
        """
        pass

    def test__sandbox_deny_application(self):
        """Test case for _sandbox_deny_application

        (Sandbox) Deny Application  # noqa: E501
        """
        pass

    def test__sandbox_reject_document(self):
        """Test case for _sandbox_reject_document

        (Sandbox) Reject Document  # noqa: E501
        """
        pass

    def test__sandbox_return_ach_payment(self):
        """Test case for _sandbox_return_ach_payment

        (Sandbox) Return ACH Payment  # noqa: E501
        """
        pass

    def test__sandbox_simulate_atm_withdrawal(self):
        """Test case for _sandbox_simulate_atm_withdrawal

        (Sandbox) Simulate ATM Withdrawal  # noqa: E501
        """
        pass

    def test__sandbox_simulate_authorization(self):
        """Test case for _sandbox_simulate_authorization

        (Sandbox) Simulate Authorization  # noqa: E501
        """
        pass

    def test__sandbox_simulate_incoming_ach_payment(self):
        """Test case for _sandbox_simulate_incoming_ach_payment

        (Sandbox) Simulate Incoming ACH Payment  # noqa: E501
        """
        pass

    def test__sandbox_simulate_incoming_wire_payment(self):
        """Test case for _sandbox_simulate_incoming_wire_payment

        (Sandbox) Simulate Incoming Wire Payment  # noqa: E501
        """
        pass

    def test__sandbox_simulate_purchase(self):
        """Test case for _sandbox_simulate_purchase

        (Sandbox) Simulate Purchase  # noqa: E501
        """
        pass

    def test__sandbox_simulate_purchase_reversal(self):
        """Test case for _sandbox_simulate_purchase_reversal

        (Sandbox) Simulate Purchase Reversal  # noqa: E501
        """
        pass

    def test__sandbox_transmit_ach_payment(self):
        """Test case for _sandbox_transmit_ach_payment

        (Sandbox) Transmit ACH Payment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
