"""
    UnitAPI

    Edit the variables with your API Token and API Server.  You can create an API token in Unit Dashboard.   # noqa: E501

    The version of the OpenAPI document: dfec2411-22b5-4a3b-8d43-fcf778bd42a5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.statements_api import StatementsApi  # noqa: E501


class TestStatementsApi(unittest.TestCase):
    """StatementsApi unit test stubs"""

    def setUp(self):
        self.api = StatementsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_statement_html(self):
        """Test case for get_statement_html

        Get Statement HTML  # noqa: E501
        """
        pass

    def test_getall0(self):
        """Test case for getall0

        Get all  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
