"""
    UnitAPI

    Edit the variables with your API Token and API Server.  You can create an API token in Unit Dashboard.   # noqa: E501

    The version of the OpenAPI document: dfec2411-22b5-4a3b-8d43-fcf778bd42a5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
200DataAttributesAddress
200DataAttributesOfficerFullName
200DataAttributesOfficerPhone
from openapi_client.model.200_data_attributes_beneficial_owners import 200DataAttributesBeneficialOwners


class Test200DataAttributesBeneficialOwners(unittest.TestCase):
    """200DataAttributesBeneficialOwners unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test200DataAttributesBeneficialOwners(self):
        """Test 200DataAttributesBeneficialOwners"""
        # FIXME: construct object with mandatory attributes with example values
        # model = 200DataAttributesBeneficialOwners()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
