"""
    UnitAPI

    Edit the variables with your API Token and API Server.  You can create an API token in Unit Dashboard.   # noqa: E501

    The version of the OpenAPI document: dfec2411-22b5-4a3b-8d43-fcf778bd42a5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.webhooks_api import WebhooksApi  # noqa: E501


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dispatch_event(self):
        """Test case for dispatch_event

        Dispatch Event  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
