"""
    UnitAPI

    Edit the variables with your API Token and API Server.  You can create an API token in Unit Dashboard.   # noqa: E501

    The version of the OpenAPI document: dfec2411-22b5-4a3b-8d43-fcf778bd42a5
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.payments_api import PaymentsApi  # noqa: E501


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self):
        self.api = PaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_ach_payment_inlinecounterparty(self):
        """Test case for create_ach_payment_inlinecounterparty

        Create ACH Payment - Inline counterparty  # noqa: E501
        """
        pass

    def test_get5(self):
        """Test case for get5

        Get  # noqa: E501
        """
        pass

    def test_getall4(self):
        """Test case for getall4

        Get all  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
