"""
    UnitAPI

    Edit the variables with your API Token and API Server.  You can create an API token in Unit Dashboard.   # noqa: E501

    The version of the OpenAPI document: dfec2411-22b5-4a3b-8d43-fcf778bd42a5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.model200_data import Model200Data
globals()['200Data'] = 200Data
from openapi_client.model.model200 import Model200


class TestModel200(unittest.TestCase):
    """Model200 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModel200(self):
        """Test Model200"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Model200()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
